/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as FinancialsRouteImport } from './routes/financials'
import { Route as HouseholdRouteImport } from './routes/household'
import { Route as DataIndexRouteImport } from './routes/data.index'
import { Route as DataDatasetIdRouteImport } from './routes/data.$datasetId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialsRoute = FinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdRoute = HouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => rootRouteImport,
} as any)
const DataIndexRoute = DataIndexRouteImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDatasetIdRoute = DataDatasetIdRouteImport.update({
  id: '/data/$datasetId',
  path: '/data/$datasetId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/financials': typeof FinancialsRoute
  '/household': typeof HouseholdRoute
  '/data/$datasetId': typeof DataDatasetIdRoute
  '/data/': typeof DataIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/financials': typeof FinancialsRoute
  '/household': typeof HouseholdRoute
  '/data/$datasetId': typeof DataDatasetIdRoute
  '/data': typeof DataIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/financials': typeof FinancialsRoute
  '/household': typeof HouseholdRoute
  '/data/$datasetId': typeof DataDatasetIdRoute
  '/data/': typeof DataIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/financials'
    | '/household'
    | '/data/$datasetId'
    | '/data/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/financials'
    | '/household'
    | '/data/$datasetId'
    | '/data'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/financials'
    | '/household'
    | '/data/$datasetId'
    | '/data/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  FinancialsRoute: typeof FinancialsRoute
  HouseholdRoute: typeof HouseholdRoute
  DataDatasetIdRoute: typeof DataDatasetIdRoute
  DataIndexRoute: typeof DataIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financials': {
      id: '/financials'
      path: '/financials'
      fullPath: '/financials'
      preLoaderRoute: typeof FinancialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/household': {
      id: '/household'
      path: '/household'
      fullPath: '/household'
      preLoaderRoute: typeof HouseholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/': {
      id: '/data/'
      path: '/data'
      fullPath: '/data/'
      preLoaderRoute: typeof DataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/$datasetId': {
      id: '/data/$datasetId'
      path: '/data/$datasetId'
      fullPath: '/data/$datasetId'
      preLoaderRoute: typeof DataDatasetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  FinancialsRoute: FinancialsRoute,
  HouseholdRoute: HouseholdRoute,
  DataDatasetIdRoute: DataDatasetIdRoute,
  DataIndexRoute: DataIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
